### PR TITLE
Added limitations to Gisgraphy

### LINKED ISSUE #72: Improve gisgraphy geocoding docs
- add that locale parameter has no effect. 
 - fix list for radius and country - looks wrongly formatted

### PR DESCRIPTION
**Pull request by boldtrn**
Fixes #72. I added information about the not supported locale and named it "limitations".

> fix list for radius and country - looks wrongly formatted

What do you mean here?

### CODE REVIEW

**Comment by karussell** [comment]
I mean this 

image

**Comment by boldtrn** [comment]
Thanks, this looks indeed weird. I changed `-` to `*`, maybe this will solve the issue?

**Comment by karussell** [comment]
Ah, I think it is the missing new line before the list: https://raw.githubusercontent.com/graphhopper/directions-api/master/index.md

**Comment by boldtrn** [comment]
That would have been my next guess. It works correctly in Github though. Will change it.

**Comment by karussell** [comment]
We use http://www.mkdocs.org/

**Comment by karussell** [comment]
Thanks!

**Pull request merged**
